fixed input Placeholder text at footer
quizardhq/frontend pull request #101
Opened 2023-05-10 14:28 UTC by Mide001

2023-05-10 14:47 UTC, dpkreativ requested changes
this fixes the waitlist form in the footer, but doesn't fix the one in the hero section. We need to make it dynamic in a way that makes it work for both places

2023-05-10 14:47 UTC, dpkreativ commented on components/ui/molecules/JoinWaitlist.tsx
This works for the footer, but if you look at the form in the hero section, it's no longer showing because of that text

2023-05-10 15:05 UTC, Mide001 commented
Oops let me confirm and fix that

2023-05-10 21:20 UTC, Mide001 reviewed
fixed

2023-05-11 13:02 UTC, dpkreativ requested changes
It's still hasn't been fixed. Check the live preview to verify what I'm saying
https://deploy-preview-101--quizardhq.netlify.app/

Let me suggest using a ternary operator to add display different classNames using `true` or `false`

Something like:

```jsx
className={`w-full outline-none bg-transparent rounded-md m-3 placeholder:text-[${isLight ? "#00A65B" : "#00e47a"}]`}
```

Then replace `placeholderColor` with `isLight`, and in the ComingSoon file, add `isLight` as a prop.

Be sure to lint your code to ensure there are no errors

2023-05-12 08:48 UTC, dpkreativ approved these changes

2023-05-12 08:48 UTC, merged